// <auto-generated />

using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;

namespace SchoolManagement.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(SchoolContext))]
    [Migration("20210404022809_RequestTable")]
    partial class RequestTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SchoolManagement.Domain.SchoolAggregate.Groups.Group", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("FormTutorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<byte>("Number")
                        .HasColumnName("Number")
                        .HasColumnType("tinyint");

                    b.Property<Guid>("SchoolId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Sign")
                        .IsRequired()
                        .HasColumnName("Sign")
                        .HasColumnType("nvarchar(4)")
                        .HasMaxLength(4);

                    b.Property<Guid?>("TreasurerId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("FormTutorId");

                    b.HasIndex("SchoolId");

                    b.HasIndex("TreasurerId")
                        .IsUnique()
                        .HasFilter("[TreasurerId] IS NOT NULL");

                    b.HasIndex("Number", "Sign")
                        .HasName("Index_Code");

                    b.ToTable("Groups","management");
                });

            modelBuilder.Entity("SchoolManagement.Domain.SchoolAggregate.Members.Member", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnName("Email")
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnName("FirstName")
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<int>("Gender")
                        .HasColumnName("Gender")
                        .HasColumnType("int");

                    b.Property<Guid?>("GroupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnName("LastName")
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<int>("Role")
                        .HasColumnName("Role")
                        .HasColumnType("int");

                    b.Property<Guid>("SchoolId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("GroupId");

                    b.HasIndex("SchoolId");

                    b.ToTable("Members","management");
                });

            modelBuilder.Entity("SchoolManagement.Domain.SchoolAggregate.Schools.School", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(3000)")
                        .HasMaxLength(3000);

                    b.Property<int?>("GroupMembersLimit")
                        .HasColumnType("int");

                    b.Property<string>("LogoId")
                        .HasColumnType("nvarchar(36)")
                        .HasMaxLength(36);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(500)")
                        .HasMaxLength(500);

                    b.Property<byte>("YearsOfEducation")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.ToTable("Schools","management");
                });

            modelBuilder.Entity("SharedKernel.Infrastructure.Concretes.Models.ClientRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("requests","idreq");
                });

            modelBuilder.Entity("SchoolManagement.Domain.SchoolAggregate.Groups.Group", b =>
                {
                    b.HasOne("SchoolManagement.Domain.SchoolAggregate.Members.Member", "FormTutor")
                        .WithMany()
                        .HasForeignKey("FormTutorId");

                    b.HasOne("SchoolManagement.Domain.SchoolAggregate.Schools.School", "School")
                        .WithMany("Groups")
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchoolManagement.Domain.SchoolAggregate.Members.Member", "Treasurer")
                        .WithOne()
                        .HasForeignKey("SchoolManagement.Domain.SchoolAggregate.Groups.Group", "TreasurerId");
                });

            modelBuilder.Entity("SchoolManagement.Domain.SchoolAggregate.Members.Member", b =>
                {
                    b.HasOne("SchoolManagement.Domain.SchoolAggregate.Groups.Group", "Group")
                        .WithMany("Students")
                        .HasForeignKey("GroupId");

                    b.HasOne("SchoolManagement.Domain.SchoolAggregate.Schools.School", "School")
                        .WithMany("Members")
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
